services:
    # Mailer Service
    eschmar_mailer:
        class: Eschmar\MailerBundle\Service\Mailer
        arguments: ['@mailer', '@twig']

    Eschmar\MailerBundle\Service\Mailer: '@eschmar_mailer'